// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/v1/stream.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/llamerada-jp/trial-connect/proto/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StreamServiceName is the fully-qualified name of the StreamService service.
	StreamServiceName = "proto.v1.StreamService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StreamServiceEchoProcedure is the fully-qualified name of the StreamService's Echo RPC.
	StreamServiceEchoProcedure = "/proto.v1.StreamService/Echo"
)

// StreamServiceClient is a client for the proto.v1.StreamService service.
type StreamServiceClient interface {
	Echo(context.Context, *connect.Request[v1.StreamServiceEchoRequest]) (*connect.ServerStreamForClient[v1.StreamServiceEchoResponse], error)
}

// NewStreamServiceClient constructs a client for the proto.v1.StreamService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStreamServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StreamServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	streamServiceMethods := v1.File_proto_v1_stream_proto.Services().ByName("StreamService").Methods()
	return &streamServiceClient{
		echo: connect.NewClient[v1.StreamServiceEchoRequest, v1.StreamServiceEchoResponse](
			httpClient,
			baseURL+StreamServiceEchoProcedure,
			connect.WithSchema(streamServiceMethods.ByName("Echo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// streamServiceClient implements StreamServiceClient.
type streamServiceClient struct {
	echo *connect.Client[v1.StreamServiceEchoRequest, v1.StreamServiceEchoResponse]
}

// Echo calls proto.v1.StreamService.Echo.
func (c *streamServiceClient) Echo(ctx context.Context, req *connect.Request[v1.StreamServiceEchoRequest]) (*connect.ServerStreamForClient[v1.StreamServiceEchoResponse], error) {
	return c.echo.CallServerStream(ctx, req)
}

// StreamServiceHandler is an implementation of the proto.v1.StreamService service.
type StreamServiceHandler interface {
	Echo(context.Context, *connect.Request[v1.StreamServiceEchoRequest], *connect.ServerStream[v1.StreamServiceEchoResponse]) error
}

// NewStreamServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStreamServiceHandler(svc StreamServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	streamServiceMethods := v1.File_proto_v1_stream_proto.Services().ByName("StreamService").Methods()
	streamServiceEchoHandler := connect.NewServerStreamHandler(
		StreamServiceEchoProcedure,
		svc.Echo,
		connect.WithSchema(streamServiceMethods.ByName("Echo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.v1.StreamService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StreamServiceEchoProcedure:
			streamServiceEchoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStreamServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStreamServiceHandler struct{}

func (UnimplementedStreamServiceHandler) Echo(context.Context, *connect.Request[v1.StreamServiceEchoRequest], *connect.ServerStream[v1.StreamServiceEchoResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("proto.v1.StreamService.Echo is not implemented"))
}
