// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: proto/v1/unary.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryServiceEchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryServiceEchoRequest) Reset() {
	*x = UnaryServiceEchoRequest{}
	mi := &file_proto_v1_unary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryServiceEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryServiceEchoRequest) ProtoMessage() {}

func (x *UnaryServiceEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_unary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryServiceEchoRequest.ProtoReflect.Descriptor instead.
func (*UnaryServiceEchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_unary_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryServiceEchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnaryServiceEchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryServiceEchoResponse) Reset() {
	*x = UnaryServiceEchoResponse{}
	mi := &file_proto_v1_unary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryServiceEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryServiceEchoResponse) ProtoMessage() {}

func (x *UnaryServiceEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_unary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryServiceEchoResponse.ProtoReflect.Descriptor instead.
func (*UnaryServiceEchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_unary_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryServiceEchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_v1_unary_proto protoreflect.FileDescriptor

var file_proto_v1_unary_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x6e, 0x61, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x22, 0x33, 0x0a, 0x17, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x34, 0x0a, 0x18, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x5d, 0x0a, 0x0c, 0x55,
	0x6e, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x04, 0x45,
	0x63, 0x68, 0x6f, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x6e, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x63,
	0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6c, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x64, 0x61, 0x2d, 0x6a, 0x70, 0x2f, 0x74, 0x72, 0x69, 0x61, 0x6c, 0x2d, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_v1_unary_proto_rawDescOnce sync.Once
	file_proto_v1_unary_proto_rawDescData []byte
)

func file_proto_v1_unary_proto_rawDescGZIP() []byte {
	file_proto_v1_unary_proto_rawDescOnce.Do(func() {
		file_proto_v1_unary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_unary_proto_rawDesc), len(file_proto_v1_unary_proto_rawDesc)))
	})
	return file_proto_v1_unary_proto_rawDescData
}

var file_proto_v1_unary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_unary_proto_goTypes = []any{
	(*UnaryServiceEchoRequest)(nil),  // 0: proto.v1.UnaryServiceEchoRequest
	(*UnaryServiceEchoResponse)(nil), // 1: proto.v1.UnaryServiceEchoResponse
}
var file_proto_v1_unary_proto_depIdxs = []int32{
	0, // 0: proto.v1.UnaryService.Echo:input_type -> proto.v1.UnaryServiceEchoRequest
	1, // 1: proto.v1.UnaryService.Echo:output_type -> proto.v1.UnaryServiceEchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_unary_proto_init() }
func file_proto_v1_unary_proto_init() {
	if File_proto_v1_unary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_unary_proto_rawDesc), len(file_proto_v1_unary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_unary_proto_goTypes,
		DependencyIndexes: file_proto_v1_unary_proto_depIdxs,
		MessageInfos:      file_proto_v1_unary_proto_msgTypes,
	}.Build()
	File_proto_v1_unary_proto = out.File
	file_proto_v1_unary_proto_goTypes = nil
	file_proto_v1_unary_proto_depIdxs = nil
}
